import { useEffect, useMemo, useState } from 'react';
import {
	consumePasswordLink,
	getPasswordLinkDetails,
	type PasswordLinkDetailsResponse,
	type PasswordLinkPurpose,
} from '../services/api-client';
import { PhoneNumberField } from './phone-number-field';

interface PasswordLinkScreenProps {
	token: string;
	usernameHint?: string;
	purposeHint?: PasswordLinkPurpose | null;
	onComplete: () => void;
}

function formatTimeLeft(totalSeconds: number): string {
	const days = Math.floor(totalSeconds / 86400);
	const hours = Math.floor((totalSeconds % 86400) / 3600);
	const minutes = (Math.floor(totalSeconds / 60) % 60)
		.toString()
		.padStart(2, '0');
	const seconds = Math.max(totalSeconds % 60, 0)
		.toString()
		.padStart(2, '0');

	if (days > 0) {
		return `${days}d ${hours}h ${minutes}m`;
	}

	if (hours > 0) {
		return `${hours}h ${minutes}m ${seconds}s`;
	}

	return `${minutes}:${seconds}`;
}

export function PasswordLinkScreen({
	token,
	usernameHint = '',
	purposeHint = null,
	onComplete,
}: PasswordLinkScreenProps) {
	const [details, setDetails] = useState<PasswordLinkDetailsResponse | null>(
		null,
	);
	const [loading, setLoading] = useState(true);
	const [submitting, setSubmitting] = useState(false);
	const [error, setError] = useState('');
	const [success, setSuccess] = useState('');
	const [phoneNumber, setPhoneNumber] = useState('');
	const [newPassword, setNewPassword] = useState('');
	const [confirmPassword, setConfirmPassword] = useState('');
	const [now, setNow] = useState(Date.now());

	useEffect(() => {
		let cancelled = false;

		async function load() {
			setLoading(true);
			setError('');
			try {
				const result = await getPasswordLinkDetails(token);
				if (!cancelled) {
					setDetails(result);
				}
			} catch (err) {
				if (!cancelled) {
					setError(
						err instanceof Error
							? err.message
							: 'This password link is invalid or expired.',
					);
				}
			} finally {
				if (!cancelled) {
					setLoading(false);
				}
			}
		}

		void load();

		return () => {
			cancelled = true;
		};
	}, [token]);

	useEffect(() => {
		if (!details?.expiresAt || success) {
			return;
		}

		const interval = window.setInterval(() => {
			setNow(Date.now());
		}, 1000);

		return () => window.clearInterval(interval);
	}, [details?.expiresAt, success]);

	const effectivePurpose = details?.purpose ?? purposeHint ?? 'reset-password';
	const effectiveUsername = details?.username ?? usernameHint;
	const expiresAtMs = details ? new Date(details.expiresAt).getTime() : 0;
	const secondsLeft = Math.max(Math.floor((expiresAtMs - now) / 1000), 0);
	const isExpired = Boolean(details) && secondsLeft <= 0;
	const passwordsMatch = newPassword === confirmPassword;
	const canSubmit =
		!loading &&
		!submitting &&
		!isExpired &&
		phoneNumber.trim().length > 0 &&
		newPassword.trim().length >= 6 &&
		passwordsMatch;

	const heading = useMemo(() => {
		return effectivePurpose === 'setup-password'
			? 'Set Your Password'
			: 'Reset Your Password';
	}, [effectivePurpose]);

	const description =
		effectivePurpose === 'setup-password'
			? 'This link was generated by an admin so you can finish setting up your account and save your phone number.'
			: 'This link was generated by an admin so you can reset your password after confirming the phone number on your profile.';

	async function handleSubmit(e: React.FormEvent) {
		e.preventDefault();
		if (!canSubmit) {
			return;
		}

		setSubmitting(true);
		setError('');
		setSuccess('');

		try {
			const result = await consumePasswordLink(token, newPassword, phoneNumber);
			setSuccess(result.message);
			window.setTimeout(onComplete, 1200);
		} catch (err) {
			setError(
				err instanceof Error
					? err.message
					: 'Failed to update password using this link.',
			);
		} finally {
			setSubmitting(false);
		}
	}

	return (
		<div className='min-h-screen bg-linear-to-br from-indigo-50 to-sky-50 flex items-center justify-center p-4'>
			<div className='w-full max-w-md rounded-3xl bg-white p-8 shadow-2xl'>
				<div className='mb-6 text-center'>
					<div className='mx-auto mb-4 inline-flex h-16 w-16 items-center justify-center rounded-2xl bg-indigo-500 text-3xl text-white shadow-lg'>
						🔐
					</div>
					<h1 className='text-2xl font-bold text-gray-800'>{heading}</h1>
					<p className='mt-2 text-sm text-gray-500'>{description}</p>
				</div>

				{loading && (
					<div className='rounded-xl border border-gray-100 bg-gray-50 px-4 py-5 text-center text-sm text-gray-500'>
						Validating link…
					</div>
				)}

				{!loading && error && (
					<div className='space-y-4'>
						<div className='rounded-xl border border-red-100 bg-red-50 px-4 py-3 text-sm text-red-600'>
							{error}
						</div>
						<button
							type='button'
							onClick={onComplete}
							className='w-full rounded-lg bg-gray-100 px-4 py-2.5 text-sm font-semibold text-gray-700 transition-colors hover:bg-gray-200'
						>
							Back To Sign In
						</button>
					</div>
				)}

				{!loading && !error && details && (
					<form onSubmit={handleSubmit} className='space-y-4'>
						<div className='rounded-xl border border-indigo-100 bg-indigo-50 px-4 py-3 text-sm text-indigo-700'>
							This link expires in{' '}
							<span className='font-bold'>{formatTimeLeft(secondsLeft)}</span>.
						</div>

						{isExpired && (
							<div className='rounded-xl border border-amber-100 bg-amber-50 px-4 py-3 text-sm text-amber-700'>
								This link has expired. Ask an admin to generate a new one.
							</div>
						)}

						{success && (
							<div className='rounded-xl border border-green-100 bg-green-50 px-4 py-3 text-sm text-green-700'>
								{success}
							</div>
						)}

						<div>
							<label className='mb-1 block text-sm font-medium text-gray-600'>
								Username
							</label>
							<input
								type='text'
								value={effectiveUsername}
								readOnly
								className='w-full rounded-lg border border-gray-200 bg-gray-50 px-3 py-2.5 text-sm text-gray-500'
							/>
						</div>

						<div>
							<label className='mb-1 block text-sm font-medium text-gray-600'>
								Phone Number
							</label>
							<PhoneNumberField
								value={phoneNumber}
								onChange={setPhoneNumber}
								placeholder={
									effectivePurpose === 'setup-password'
										? 'Enter your phone number'
										: 'Enter the phone number saved on your profile'
								}
							/>
							<p className='mt-1 text-xs text-gray-500'>
								{effectivePurpose === 'setup-password'
									? 'This number is required and will be saved to your profile. It must be unique.'
									: 'Enter the same number already saved on your profile to continue.'}
							</p>
						</div>

						<div>
							<label className='mb-1 block text-sm font-medium text-gray-600'>
								New Password
							</label>
							<input
								type='password'
								value={newPassword}
								onChange={(e) => setNewPassword(e.target.value)}
								disabled={isExpired || Boolean(success)}
								placeholder='At least 6 characters'
								className='w-full rounded-lg border border-gray-300 px-3 py-2.5 text-sm focus:border-indigo-500 focus:outline-none focus:ring-2 focus:ring-indigo-500 disabled:opacity-50'
							/>
						</div>

						<div>
							<label className='mb-1 block text-sm font-medium text-gray-600'>
								Confirm Password
							</label>
							<input
								type='password'
								value={confirmPassword}
								onChange={(e) => setConfirmPassword(e.target.value)}
								disabled={isExpired || Boolean(success)}
								placeholder='Re-enter your new password'
								className='w-full rounded-lg border border-gray-300 px-3 py-2.5 text-sm focus:border-indigo-500 focus:outline-none focus:ring-2 focus:ring-indigo-500 disabled:opacity-50'
							/>
							{confirmPassword && !passwordsMatch && (
								<p className='mt-1 text-xs text-red-500'>
									Passwords do not match.
								</p>
							)}
						</div>

						<button
							type='submit'
							disabled={!canSubmit || Boolean(success)}
							className='w-full rounded-lg bg-indigo-500 px-4 py-2.5 text-sm font-semibold text-white transition-colors hover:bg-indigo-600 disabled:cursor-not-allowed disabled:opacity-50'
						>
							{submitting
								? 'Saving…'
								: effectivePurpose === 'setup-password'
									? 'Set Password'
									: 'Reset Password'}
						</button>

						<button
							type='button'
							onClick={onComplete}
							className='w-full text-sm font-medium text-gray-500 transition-colors hover:text-gray-700'
						>
							Back To Sign In
						</button>
					</form>
				)}
			</div>
		</div>
	);
}
